### ISSUE TITLE
non-latin symbols

### ISSUE THREAD

**Issue by vaswork** [highmobility/hm-android-sdk#1]
[excuse my Eng]

Messages with non-english words is not displaying at all. 
Example with cyrillic letters:

"2017-10-21 14:42\r\nDriver: Шарик, 16 y.o. (RU)"

No any messages on head-unit.

HM-Log contains incomming message:

14:43:59 - Android Meizu - CapabilityManager - Incoming telematics message for Messaging - ADcADkhlYWx0aGVkZXMgT05FAC0yMDE3LTEwLTIxIDE0OjQzDQpEcml2ZXI6INCo0LDRgNC40LosIDE2IHkuby4gKFJVKQ==. 

Telematic API.

Slava.

**Comment by kevinvaldek** [comment]
Thanks @vaswork - issue confirmed to be in the Car Emulator. Will keep you posted.

**Comment by kevinvaldek** [comment]
This was resolved with the release of Car Emulator 3.0
