### ISSUE TITLE
next line

### ISSUE THREAD

**Issue by vaswork** [highmobility/hm-android-sdk#2]
[excuse my Eng]

"\r\n" escape sequence is not working as expected.

For example. Telematic API. Messaging and Notifications:

The message string:
"2017-10-21 15:26\r\nDriver: Slawa, 56 y.o. (RU)"

HM-LOG contains two records:

15:27:30 - Android Meizu - CapabilityManager - Incoming telematics message for Messaging - ADcADkhlYWx0aGVkZXMgT05FAC0yMDE3LTEwLTIxIDE1OjI2DQpEcml2ZXI6IFNsYXdhLCA1NiB5Lm8uIChSVSk=. 

15:27:30 - Android Meizu - Messaging - 0x00 0x37 0x01 - Received message: "2017-10-21 15:26

Driver: Slawa, 56 y.o. (RU)", Sender handle: Healthedes ONE 

But the message on head-unit in one line:
MESSAGE RECEIVED FROM: HEALTHEDES ONE
2017-10-21 15:26 Driver: Slawa, 56 y.o. (RU)

Would be nice to have "next-line" feature for long structured messages.

Slava.

PS: The same behaviour with notifications.

**Comment by kevinvaldek** [comment]
This was resolved with the release of Car Emulator 3.0
